- name: Generar reporte en pantalla (vía raw) de FortiGate
  hosts: FORTI1                  # o tu grupo/inventario de FortiGate
  gather_facts: no
  vars:
    fecha: "{{ lookup('pipe', 'date +%Y-%m-%d') }}"
  tasks:

    - name: Obtener SYSTEM STATUS
      raw: get system status
      register: system_status

    - name: Obtener PERFORMANCE STATUS
      raw: get system performance status
      register: performance_status

    - name: Obtener SESSION STATUS
      raw: get system session status
      register: session_status

    - name: Obtener HARDWARE STATUS
      raw: get hardware status
      register: hardware_status

    # ════════════════════════════════════════════════════════════════
    # Reporte legible en pantalla
    # ════════════════════════════════════════════════════════════════
    - name: Mostrar reporte formateado
      ansible.builtin.debug:
        msg: |
          ══════════════════════════════════════════════════════
          ▸ REPORTE SEMANAL FORTIGATE
          ▸ Fecha : {{ fecha }}
          ▸ Equipo: {{ inventory_hostname }}
          ══════════════════════════════════════════════════════

          ▶ SYSTEM STATUS
          {{ system_status.stdout }}

          ▶ PERFORMANCE STATUS
          {{ performance_status.stdout }}

          ▶ SESSION STATUS
          {{ session_status.stdout }}

          ▶ HARDWARE STATUS
          {{ hardware_status.stdout }}

          ══════════════════════════════════════════════════════

