- name: Generar reporte en pantalla desde FortiGate (solo comandos del KB)
  hosts: FORTI1
  gather_facts: no
  vars:
    fecha: "{{ lookup('pipe', 'date +%Y-%m-%d') }}"
  tasks:

    - name: Obtener SYSTEM STATUS
      raw: get system status
      register: system_status

    - name: Obtener PERFORMANCE STATUS
      raw: get system performance status
      register: performance_status

    - name: Obtener SESSION STATUS
      raw: get system session status
      register: session_status

    - name: Obtener HARDWARE STATUS
      raw: get hardware status
      register: hardware_status

    - name: Obtener INTERFACE STATUS
      raw: get system interface
      register: interface_status

    - name: Obtener USO DE MEMORIA
      raw: diag hardware sysinfo memory
      register: memory_status

    - name: Obtener MEMORIA SHARED
      raw: diag hard sysinfo shm
      register: shared_memory

    - name: Obtener CRASHLOGS
      raw: diag debug crashlog read
      register: crashlog

    - name: Mostrar reporte formateado y legible
      debug:
        msg: |
          ══════════════════════════════════════════════════════
          ▸ REPORTE SEMANAL FORTIGATE
          ▸ Fecha : {{ fecha }}
          ▸ Equipo: {{ inventory_hostname }}
          ══════════════════════════════════════════════════════

          ▶ SYSTEM STATUS
          {% for line in system_status.stdout_lines %}{{ line }}
          {% endfor %}

          ▶ PERFORMANCE STATUS
          {% for line in performance_status.stdout_lines %}{{ line }}
          {% endfor %}

          ▶ SESSION STATUS
          {% for line in session_status.stdout_lines %}{{ line }}
          {% endfor %}

          ▶ HARDWARE STATUS
          {% for line in hardware_status.stdout_lines %}{{ line }}
          {% endfor %}

          ▶ INTERFACE STATUS
          {% for line in interface_status.stdout_lines %}{{ line }}
          {% endfor %}

          ▶ USO DE MEMORIA
          {% for line in memory_status.stdout_lines %}{{ line }}
          {% endfor %}

          ▶ MEMORIA COMPARTIDA
          {% for line in shared_memory.stdout_lines %}{{ line }}
          {% endfor %}

          ▶ CRASHLOGS
          {% for line in crashlog.stdout_lines %}{{ line }}
          {% endfor %}

          ══════════════════════════════════════════════════════

