---
- name: Verificar licencias y actualizaciones en FortiGates
  hosts: localhost
  gather_facts: false
  vars:
    fgt_token: "{{ lookup('env', 'FGT_TOKEN') }}"
  tasks:

    - name: Ejecutar revisión por cada FortiGate
      include_tasks: check_license_fgt.yml
      loop: "{{ groups['fortigates'] }}"
      loop_control:
        loop_var: fgt_host

