---
- name: Mostrar interfaces WAN disponibles en FortiGate
  hosts: FORTI1
  gather_facts: no

  tasks:
    - name: Obtener configuración de interfaces
      raw: "show system interface"
      register: interfaces_output

    - name: Mostrar contenido de las interfaces WAN
      debug:
        msg: "{{ interfaces_output.stdout }}"

    - name: Extraer bloques de interfaz
      set_fact:
        interface_blocks: >-
          {{
            interfaces_output.stdout.split('edit "') | map('regex_replace', '^(.*?)"\\n', '\\1::\\g<1>') | list
          }}

    - name: Filtrar interfaces con rol WAN
      set_fact:
        wan_interfaces: >-
          {{
            interface_blocks
            | select('search', 'set role wan')
            | map('regex_replace', '^(.*?)::.*$', '\\1')
            | list
          }}

    - name: Extraer solo nombres de interfaces WAN
      set_fact:
        wan_interface_names: >-
          {{
            wan_interfaces
            | map('regex_search', '^([a-zA-Z0-9_-]+)')
            | list
          }}

    - name: Extraer direcciones IP de las interfaces WAN utilizando números y puntos
      set_fact:
        wan_interface_ips: >-
          {{
            wan_interfaces
            | map('regex_search', 'set ip\s+(\d+\.\d+\.\d+\.\d+)')
            | list
          }}

    - name: Mostrar nombres de interfaces WAN
      debug:
        msg: "Nombres de interfaces WAN: {{ wan_interface_names }}"

    - name: Mostrar direcciones IP de interfaces WAN
      debug:
        msg: "Direcciones IP de interfaces WAN: {{ wan_interface_ips }}"

---
- name: Mostrar interfaces WAN disponibles en FortiGate
  hosts: FORTI1
  gather_facts: no

  tasks:
    - name: Obtener configuración de interfaces
      raw: "show system interface"
      register: interfaces_output

    - name: Mostrar contenido de las interfaces WAN
      debug:
        msg: "{{ interfaces_output.stdout }}"

    - name: Extraer bloques de interfaz
      set_fact:
        interface_blocks: >-
          {{
            interfaces_output.stdout.split('edit "') | map('regex_replace', '^(.*?)"\\n', '\\1::\\g<1>') | list
          }}

    - name: Filtrar interfaces con rol WAN
      set_fact:
        wan_interfaces: >-
          {{
            interface_blocks
            | select('search', 'set role wan')
            | map('regex_replace', '^(.*?)::.*$', '\\1')
            | list
          }}

    - name: Extraer solo nombres de interfaces WAN
      set_fact:
        wan_interface_names: >-
          {{
            wan_interfaces
            | map('regex_search', '^([a-zA-Z0-9_-]+)')
            | list
          }}

    - name: Extraer direcciones IP de las interfaces WAN utilizando números y puntos
      set_fact:
        wan_interface_ips: >-
          {{
            wan_interfaces
            | map('regex_search', 'set ip\s+(\d+\.\d+\.\d+\.\d+)')
            | list
          }}

    - name: Mostrar nombres de interfaces WAN
      debug:
        msg: "Nombres de interfaces WAN: {{ wan_interface_names }}"

    - name: Mostrar direcciones IP de interfaces WAN
      debug:
        msg: "Direcciones IP de interfaces WAN: {{ wan_interface_ips }}"

